import BottomBar from "@/components/BottomBar";
import NavBar from "@/components/NavBar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Nuvex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className="bg-[#1c1c1c] text-[white] font-['Ubuntu',_sans-serif] font-normal not-italic"
      >
        <NavBar />
        <div className="h-[90vh] overflow-y-scroll">{children}</div>
        <BottomBar />
      </body>
    </html>
  );
}
